# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/juank/flujoDeCalor/flujoDeCalor.cache/wt [current_project]
set_property parent.project_path /home/juank/flujoDeCalor/flujoDeCalor.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/juank/flujoDeCalor/flujoDeCalor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/juank/flujoDeCalor/ram.coe
read_vhdl -library xil_defaultlib {
  /home/juank/flujoDeCalor/flujoDeCalor.srcs/sources_1/new/arrayStdLogicVector.vhd
  /home/juank/flujoDeCalor/flujoDeCalor.srcs/sources_1/new/calculoDeCelda.vhd
  /home/juank/flujoDeCalor/flujoDeCalor.srcs/sources_1/new/flujoDeCalor.vhd
}
read_ip -quiet /home/juank/flujoDeCalor/flujoDeCalor.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/juank/flujoDeCalor/flujoDeCalor.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files /home/juank/flujoDeCalor/flujoDeCalor.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top flujoDeCalor -part xc7a100tcsg324-1


write_checkpoint -force -noxdef flujoDeCalor.dcp

catch { report_utilization -file flujoDeCalor_utilization_synth.rpt -pb flujoDeCalor_utilization_synth.pb }
